const COMMON = {
  SWIPE_DOWN_PERSENTAGE: 25 /* % */,
}

const HOMESCREEN = {
  BLUR_MAX: 30 /* px */,
  BRIGHTNESS_MAX: 75 /* % */,
  TRANSITION_DURATION: 278 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'cubic-bezier(0.38, 0, 0.62, 1.0)'
}

const KEYBOARD = {
  TRANSITION_DURATION: 328 /* ms */,
  OPEN_TRANSITION_TIMING_FUNCTION: 'cubic-bezier(0, 0, 0.15, 1.0)',
  CLOSE_TRANSITION_TIMING_FUNCTION: 'cubic-bezier(0, 0, 0.62, 1.0)'
}

const SPOTLIGHT = {
  TRANSITION_DURATION: 174 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'cubic-bezier(0.42, 0, 1.0, 1.0)'
}

export { COMMON, HOMESCREEN, KEYBOARD, SPOTLIGHT }