const COMMON = {
  SWIPE_DOWN_PERSENTAGE: 35 /* % */,
}

const HOMESCREEN = {
  BLUR_MAX: 40 /* px */,
  BRIGHTNESS_MAX: 65 /* % */,
  TRANSITION_DURATION: 295 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'cubic-bezier(0.42, 0, 0.58, 1.0)'
}

const KEYBOARD = {
  TRANSITION_DURATION: 336 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'cubic-bezier(0, 0, 0.15, 1.0)'
}

const SPOTLIGHT = {
  TRANSITION_DURATION: 174 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'cubic-bezier(0.42, 0, 1.0, 1.0)'
}

export { COMMON, HOMESCREEN, KEYBOARD, SPOTLIGHT }