const COMMON = {
  SWIPE_DOWN_PERSENTAGE: 35 /* % */,
}

const HOMESCREEN = {
  BLUR_MAX: 40 /* px */,
  BRIGHTNESS_MAX: 65 /* % */,
  SWIPE_DOWN_PERSENTAGE: 35 /* % */,
  TRANSITION_DURATION: 300 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'ease'
}

const KEYBOARD = {
  TRANSITION_DURATION: 200 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'ease-out'
}

const SPOTLIGHT = {
  TRANSITION_DURATION: 200 /* ms */,
  TRANSITION_TIMING_FUNCTION: 'ease-out'
}

export { COMMON, HOMESCREEN, KEYBOARD, SPOTLIGHT }